"use client"

import { Container } from "@/components/ui/container"
import { Header } from "@/components/marketing/layout/header"
import { Footer } from "@/components/marketing/layout/footer"
import {
  RiShieldCheckLine,
  RiLockLine,
  RiEyeLine,
  RiUserLine,
  RiGlobalLine,
  RiMailLine,
} from "react-icons/ri"

export default function PrivacyPage() {
  const lastUpdated = "November 8, 2025"

  const sections = [
    {
      title: "1. Information We Collect",
      icon: RiEyeLine,
      content: [
        {
          subtitle: "Account Information",
          text: "When you create an account, we collect your name, email address, password (encrypted), and optional company information. This information is necessary to provide our services and manage your account.",
        },
        {
          subtitle: "Voice Data",
          text: "When you use our voice cloning features, we temporarily store the audio files you upload to train custom voice models. Voice clones and their metadata are associated with your account. You can delete voice clones at any time.",
        },
        {
          subtitle: "Generated Content",
          text: "We temporarily store the text inputs you provide and the audio outputs generated by our AI models. Generated audio files are automatically deleted after 1 hour unless you choose to download them. Text inputs are retained for analytics purposes only.",
        },
        {
          subtitle: "Usage Data",
          text: "We automatically collect information about how you interact with our services, including: feature usage, API calls, character counts, model selections, generation timestamps, error logs, and browser/device information.",
        },
        {
          subtitle: "Payment Information",
          text: "Payment information is processed through Stripe, our payment processor. We never store your full credit card information on our servers. We only receive tokenized payment data from Stripe.",
        },
      ],
    },
    {
      title: "2. How We Use Your Information",
      icon: RiUserLine,
      content: [
        {
          subtitle: "Service Delivery",
          text: "We use your information to provide, maintain, and improve VoiceCraft services, including generating voice content, processing voice clones, managing your account, and providing customer support.",
        },
        {
          subtitle: "Communication",
          text: "We use your email address to send service-related notifications, account updates, security alerts, and (with your consent) marketing communications about new features and updates.",
        },
        {
          subtitle: "Analytics & Improvements",
          text: "We analyze usage patterns to understand how our services are used, identify bugs and issues, optimize model performance, improve user experience, and develop new features.",
        },
        {
          subtitle: "Legal Compliance",
          text: "We may use your information to comply with legal obligations, enforce our Terms of Service, protect our rights and property, prevent fraud and abuse, and respond to lawful requests from authorities.",
        },
      ],
    },
    {
      title: "3. Data Sharing and Disclosure",
      icon: RiGlobalLine,
      content: [
        {
          subtitle: "Third-Party Service Providers",
          text: "We share data with trusted service providers who assist us in operating our platform: Replicate (AI model hosting), Stripe (payment processing), AWS/Cloud providers (infrastructure), Analytics services (usage tracking). All providers are contractually bound to protect your data.",
        },
        {
          subtitle: "AI Model Providers",
          text: "Your text inputs and generation requests are sent to Replicate's infrastructure to run AI models (Kokoro-82M, Minimax, XTTS-v2). Replicate's privacy policy governs their data handling. We have data processing agreements in place with all AI providers.",
        },
        {
          subtitle: "Legal Requirements",
          text: "We may disclose your information if required by law, in response to valid legal requests (subpoenas, court orders), to protect our rights or property, to prevent fraud or security threats, or in connection with a business transfer or acquisition.",
        },
        {
          subtitle: "With Your Consent",
          text: "We will share your information with third parties only when you explicitly consent to such sharing. For example, if you choose to publish generated content publicly or share voice clones with team members.",
        },
      ],
    },
    {
      title: "4. Data Security",
      icon: RiShieldCheckLine,
      content: [
        {
          subtitle: "Encryption",
          text: "All data is encrypted in transit using TLS 1.3 and at rest using AES-256 encryption. Passwords are hashed using bcrypt with salt. API keys and tokens are encrypted before storage.",
        },
        {
          subtitle: "Access Controls",
          text: "We implement strict access controls and authentication mechanisms. Multi-factor authentication (MFA) is available for all accounts. Role-based access control (RBAC) for team accounts. Regular security audits and penetration testing.",
        },
        {
          subtitle: "Infrastructure Security",
          text: "Our infrastructure is hosted on enterprise-grade cloud providers with SOC 2 Type II certification. We implement firewalls, intrusion detection systems, automated backups and disaster recovery, and regular security patches and updates.",
        },
        {
          subtitle: "Data Isolation",
          text: "Each customer's data is logically isolated. Voice clones are associated only with your account. No cross-customer data sharing or access.",
        },
      ],
    },
    {
      title: "5. Data Retention",
      icon: RiLockLine,
      content: [
        {
          subtitle: "Generated Audio",
          text: "Generated audio files are automatically deleted 1 hour after generation. If you download audio, we do not retain copies on our servers. Text inputs are retained for up to 30 days for analytics.",
        },
        {
          subtitle: "Voice Clones",
          text: "Voice clones (training audio and resulting models) are retained until you delete them or close your account. Original training audio is deleted after voice clone creation. Only the voice model is retained.",
        },
        {
          subtitle: "Account Data",
          text: "Account information is retained for as long as your account is active. After account deletion, personal data is removed within 30 days. Some data may be retained longer for legal compliance (financial records for 7 years).",
        },
        {
          subtitle: "Backup Data",
          text: "Backup copies may be retained for up to 90 days for disaster recovery purposes. Backup data is encrypted and access-controlled.",
        },
      ],
    },
    {
      title: "6. Your Rights (GDPR & CCPA)",
      icon: RiUserLine,
      content: [
        {
          subtitle: "Access & Portability",
          text: "You have the right to access your personal data and request a copy in machine-readable format. You can export your voice clones, usage history, and account data at any time through your dashboard.",
        },
        {
          subtitle: "Correction & Update",
          text: "You can update your account information at any time through your account settings. Contact us if you need assistance correcting inaccurate data.",
        },
        {
          subtitle: "Deletion",
          text: "You have the right to request deletion of your personal data. You can delete individual voice clones through your dashboard. Close your account to delete all associated data. Some data may be retained for legal compliance.",
        },
        {
          subtitle: "Objection & Restriction",
          text: "You can object to processing of your data for marketing purposes. You can request restriction of processing in certain circumstances. You can withdraw consent for optional data processing at any time.",
        },
        {
          subtitle: "Data Protection Authority",
          text: "EU residents have the right to lodge a complaint with their local data protection authority if they believe their rights have been violated.",
        },
      ],
    },
    {
      title: "7. Cookies and Tracking",
      icon: RiEyeLine,
      content: [
        {
          subtitle: "Essential Cookies",
          text: "We use essential cookies for authentication, session management, and security. These cookies are necessary for the service to function and cannot be disabled.",
        },
        {
          subtitle: "Analytics Cookies",
          text: "We use analytics cookies to understand how users interact with our services. This helps us improve the user experience and identify technical issues. You can opt out of analytics cookies in your account settings.",
        },
        {
          subtitle: "Cookie Management",
          text: "You can manage cookie preferences through your browser settings. Note that disabling essential cookies will affect service functionality. We respect Do Not Track (DNT) browser signals.",
        },
      ],
    },
  ]

  return (
    <main className="min-h-screen bg-white">
      {/* Header */}
      <Header
        logoText="VoiceCraft"
        navLinks={[
          { label: "Features", href: "/features" },
          { label: "Pricing", href: "/pricing" },
          { label: "Demo", href: "/demo" },
        ]}
        ctaButton={{
          text: "Get Started",
          href: "/signup",
        }}
      />

      {/* Hero Section */}
      <section className="py-20 border-b-8 border-black">
        <Container maxWidth="xl">
          <div className="max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-3 px-6 py-3 bg-yellow-400 border-4 border-black mb-8">
              <RiShieldCheckLine className="w-6 h-6" />
              <span className="text-sm font-bold uppercase tracking-wider">Privacy Policy</span>
            </div>
            <h1 className="text-6xl md:text-7xl font-bold uppercase mb-6 leading-tight">
              YOUR PRIVACY MATTERS
            </h1>
            <p className="text-xl text-gray-700 mb-6">
              We take your privacy seriously. This policy explains how we collect, use, protect, and share your information when you use VoiceCraft.
            </p>
            <p className="text-sm font-bold uppercase text-gray-900">
              Last Updated: {lastUpdated}
            </p>
          </div>
        </Container>
      </section>

      {/* Quick Summary */}
      <section className="py-16 bg-black border-b-8 border-yellow-400">
        <Container maxWidth="xl">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold uppercase mb-8 text-yellow-400">
              THE SHORT VERSION
            </h2>
            <div className="grid md:grid-cols-2 gap-6">
              <div className="p-6 bg-white border-4 border-white">
                <h3 className="text-lg font-bold uppercase mb-3">✓ WHAT WE COLLECT</h3>
                <p className="text-gray-700 text-sm">
                  Account info, voice data you upload, text inputs, generated audio, usage analytics, and payment data (via Stripe).
                </p>
              </div>
              <div className="p-6 bg-white border-4 border-white">
                <h3 className="text-lg font-bold uppercase mb-3">✓ HOW WE USE IT</h3>
                <p className="text-gray-700 text-sm">
                  To provide services, improve features, send updates, ensure security, and comply with legal requirements.
                </p>
              </div>
              <div className="p-6 bg-white border-4 border-white">
                <h3 className="text-lg font-bold uppercase mb-3">✓ WHO WE SHARE WITH</h3>
                <p className="text-gray-700 text-sm">
                  Service providers (Replicate, Stripe, AWS), legal authorities when required, and no one else without your consent.
                </p>
              </div>
              <div className="p-6 bg-white border-4 border-white">
                <h3 className="text-lg font-bold uppercase mb-3">✓ YOUR RIGHTS</h3>
                <p className="text-gray-700 text-sm">
                  Access, correct, delete, or export your data anytime. GDPR and CCPA compliant. Full data control.
                </p>
              </div>
            </div>
          </div>
        </Container>
      </section>

      {/* Detailed Sections */}
      <section className="py-24">
        <Container maxWidth="xl">
          <div className="max-w-4xl mx-auto space-y-16">
            {sections.map((section, sectionIndex) => {
              const Icon = section.icon
              return (
                <div key={sectionIndex} id={`section-${sectionIndex + 1}`}>
                  <div className="mb-8">
                    <div className="flex items-center gap-4 mb-4">
                      <div className="w-12 h-12 bg-black border-4 border-black flex items-center justify-center">
                        <Icon className="w-6 h-6 text-yellow-400" />
                      </div>
                      <h2 className="text-3xl font-bold uppercase">{section.title}</h2>
                    </div>
                  </div>

                  <div className="space-y-6">
                    {section.content.map((item, itemIndex) => (
                      <div
                        key={itemIndex}
                        className={`p-6 border-4 border-black ${
                          itemIndex % 2 === 0 ? "bg-white brutalist-shadow" : "bg-yellow-50"
                        }`}
                      >
                        <h3 className="text-lg font-bold uppercase mb-3">{item.subtitle}</h3>
                        <p className="text-gray-700 leading-relaxed">{item.text}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )
            })}

            {/* Additional Sections */}
            <div id="section-8">
              <div className="mb-8">
                <div className="flex items-center gap-4 mb-4">
                  <div className="w-12 h-12 bg-black border-4 border-black flex items-center justify-center">
                    <RiGlobalLine className="w-6 h-6 text-yellow-400" />
                  </div>
                  <h2 className="text-3xl font-bold uppercase">8. International Data Transfers</h2>
                </div>
              </div>

              <div className="p-6 bg-white border-4 border-black brutalist-shadow">
                <p className="text-gray-700 leading-relaxed mb-4">
                  VoiceCraft is based in the United States. If you access our services from outside the US, your information will be transferred to, stored, and processed in the United States and other countries where our service providers operate.
                </p>
                <p className="text-gray-700 leading-relaxed mb-4">
                  We ensure appropriate safeguards are in place for international data transfers, including Standard Contractual Clauses (SCCs) approved by the European Commission, adequacy decisions where available, and data processing agreements with all service providers.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  By using our services, you consent to the transfer of your information to the United States and other countries that may have different data protection laws than your country of residence.
                </p>
              </div>
            </div>

            <div id="section-9">
              <div className="mb-8">
                <div className="flex items-center gap-4 mb-4">
                  <div className="w-12 h-12 bg-black border-4 border-black flex items-center justify-center">
                    <RiUserLine className="w-6 h-6 text-yellow-400" />
                  </div>
                  <h2 className="text-3xl font-bold uppercase">9. Children's Privacy</h2>
                </div>
              </div>

              <div className="p-6 bg-white border-4 border-black brutalist-shadow">
                <p className="text-gray-700 leading-relaxed mb-4">
                  VoiceCraft is not intended for use by children under the age of 13 (or 16 in the EU). We do not knowingly collect personal information from children under these ages.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  If we become aware that we have collected personal information from a child under the applicable age without parental consent, we will take steps to delete that information as quickly as possible. If you believe we have collected information from a child, please contact us immediately at privacy@voicecraft.ai.
                </p>
              </div>
            </div>

            <div id="section-10">
              <div className="mb-8">
                <div className="flex items-center gap-4 mb-4">
                  <div className="w-12 h-12 bg-black border-4 border-black flex items-center justify-center">
                    <RiLockLine className="w-6 h-6 text-yellow-400" />
                  </div>
                  <h2 className="text-3xl font-bold uppercase">10. Changes to This Policy</h2>
                </div>
              </div>

              <div className="p-6 bg-white border-4 border-black brutalist-shadow">
                <p className="text-gray-700 leading-relaxed mb-4">
                  We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements, or other factors.
                </p>
                <p className="text-gray-700 leading-relaxed mb-4">
                  When we make material changes, we will notify you by email (to the address associated with your account) and/or by posting a notice on our website. We will also update the "Last Updated" date at the top of this policy.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  Your continued use of VoiceCraft after any changes to this Privacy Policy constitutes your acceptance of the updated policy.
                </p>
              </div>
            </div>
          </div>
        </Container>
      </section>

      {/* Contact Section */}
      <section className="py-24 bg-black border-t-8 border-yellow-400">
        <Container maxWidth="xl">
          <div className="max-w-3xl mx-auto text-center">
            <div className="w-20 h-20 bg-yellow-400 border-4 border-yellow-400 flex items-center justify-center mx-auto mb-6">
              <RiMailLine className="w-10 h-10 text-black" />
            </div>
            <h2 className="text-4xl font-bold uppercase mb-6 text-yellow-400">
              QUESTIONS ABOUT PRIVACY?
            </h2>
            <p className="text-xl text-white mb-8">
              If you have questions about this Privacy Policy or how we handle your data, we're here to help.
            </p>

            <div className="p-8 bg-white border-4 border-white brutalist-shadow-yellow">
              <h3 className="text-2xl font-bold uppercase mb-4">CONTACT US</h3>
              <div className="space-y-3 text-left max-w-2xl mx-auto">
                <div>
                  <span className="font-bold uppercase text-sm">Email:</span>
                  <br />
                  <a
                    href="mailto:privacy@voicecraft.ai"
                    className="text-lg font-bold text-black underline hover:no-underline"
                  >
                    privacy@voicecraft.ai
                  </a>
                </div>
                <div>
                  <span className="font-bold uppercase text-sm">Data Protection Officer:</span>
                  <br />
                  <a
                    href="mailto:dpo@voicecraft.ai"
                    className="text-lg font-bold text-black underline hover:no-underline"
                  >
                    dpo@voicecraft.ai
                  </a>
                </div>
                <div>
                  <span className="font-bold uppercase text-sm">Mailing Address:</span>
                  <br />
                  <address className="text-gray-700 not-italic">
                    VoiceCraft, Inc.
                    <br />
                    123 Voice Street, Suite 100
                    <br />
                    San Francisco, CA 94105
                    <br />
                    United States
                  </address>
                </div>
              </div>
            </div>
          </div>
        </Container>
      </section>

      <Footer />
    </main>
  )
}
